base for realaze db
heorhii-aksiuk/wallet-team-proj-back pull request #1
Opened 2022-05-11 20:24 UTC by Andriyer

2022-05-11 20:26 UTC, Bender148 approved these changes

2022-05-12 08:34 UTC, heorhii-aksiuk commented on .gitignore
> -# Logs
А это зачем нужно было менять? Стандартный гитигнор для Node.js

2022-05-12 08:35 UTC, heorhii-aksiuk commented on package.json
> +  "name": "template",
Название нужно было оставить

2022-05-12 08:36 UTC, heorhii-aksiuk commented on readme.md
> +## GoIT Node.js Course Template Homework
А я понял, копипаст, ну это точно лишнее тут.

2022-05-12 08:37 UTC, heorhii-aksiuk commented on app.js
> +const contactsRouter = require('./routes/api/contacts')
Какие контакты?

2022-05-12 08:48 UTC, heorhii-aksiuk requested changes
Это слепой копипаст с домашек, поудаляй лишнее.

2022-05-12 08:50 UTC, Andriyer commented
недосмотрел вчера чуток, сорри

2022-05-12 08:52 UTC, heorhii-aksiuk approved these changes

2022-05-12 08:52 UTC, merged